### ISSUE TITLE
InvalidCastException when trying to decompile a 8.2 dotsettings file

### ISSUE THREAD

**Issue by wangzq** [citizenmatt/resharper-template-compiler#1]
```
Unhandled Exception: System.InvalidCastException: Specified cast is not valid.
   at CitizenMatt.ReSharper.TemplateCompiler.SettingsDeserialisation.TryGetValue[T](IEnumerable`1 path, String name, T& value)
   at CitizenMatt.ReSharper.TemplateCompiler.SettingsDeserialisation.DeserialiseFields(IList`1 templatePath)
   at CitizenMatt.ReSharper.TemplateCompiler.SettingsDeserialisation.DeserialiseTemplate(Guid guid)
   at CitizenMatt.ReSharper.TemplateCompiler.SettingsDeserialisation.DeserialiseTemplates()
   at CitizenMatt.ReSharper.TemplateCompiler.Program.DoDecompile(DecompileOptions decompileOptions)
   at CitizenMatt.ReSharper.TemplateCompiler.Program.Main(String[] args)
```

**Comment by wangzq** [comment]
Trying to create a PR but realized I made another commit which is not necessary, learning on how to cherry-pick the correct commit and send a PR...
